Add bumper pubs, remove obsolete debug pubs.
victoriarobotics/victoria_platform pull request #42
Opened 2017-04-07 17:56 UTC by markwomack

2017-04-07 18:44 UTC, griswaldbrooks requested changes

2017-04-07 18:44 UTC, griswaldbrooks commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +  // TODO(mwomack): set header frame to what?
Set the frames to /bumper_left and /bumper_right.
We'll have to define the transformation in the urdf.

2017-04-07 18:44 UTC, griswaldbrooks commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +                            /((double)(MAX_RAW_LEFT_BUMPER - MIN_RAW_LEFT_BUMPER)));
It's preferable to use `static_cast<double>(MAX ...)`

To shorten the line width, you could 
```
static const int RANGE_RAW_LEFT_BUMPER(MAX_RAW_LEFT_BUMPER - MIN_RAW_LEFT_BUMPER);
```

2017-04-07 18:44 UTC, griswaldbrooks commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +  int callback_millis = static_cast<int>((1.0/callback_freq_hz) * 1000);
If you wanted to save one cycle you could do
```
static_cast<int>(1000.0/callback_freq_hz);
```

2017-04-07 18:53 UTC, griswaldbrooks commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +void setupTimerCallback(int callback_freq_hz, void (*callback)(void)) {
`setupTimerCallback` needs to be forward declared for `setup` to recognize it, according to travis.

2017-04-08 00:52 UTC, markwomack commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +                            /((double)(MAX_RAW_LEFT_BUMPER - MIN_RAW_LEFT_BUMPER)));
Done. Made the range a double, so I don't need to cast.

2017-04-08 00:55 UTC, markwomack commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +  // TODO(mwomack): set header frame to what?
Done.

2017-04-08 00:57 UTC, markwomack commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +  int callback_millis = static_cast<int>((1.0/callback_freq_hz) * 1000);
Done.  I don't think any cast is required.

2017-04-08 02:04 UTC, markwomack commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +void setupTimerCallback(int callback_freq_hz, void (*callback)(void)) {
Done

2017-04-08 18:52 UTC, griswaldbrooks commented on Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino
> +  int callback_millis = (1000/callback_freq_hz);
1000.f

2017-04-08 18:53 UTC, merged